# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './managerGUI/FirstVersion.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(829, 502)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color: rgb(48, 0, 121);\n"
"alternate-background-color: rgb(35, 88, 0);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.btnNewPassword = QtWidgets.QPushButton(self.centralwidget)
        self.btnNewPassword.setStyleSheet("background-color: rgb(192, 136, 205);")
        self.btnNewPassword.setObjectName("btnNewPassword")
        self.verticalLayout.addWidget(self.btnNewPassword)
        self.txtNewPassword = QtWidgets.QTextEdit(self.centralwidget)
        self.txtNewPassword.setStyleSheet("background-color: rgb(227, 90, 142);")
        self.txtNewPassword.setObjectName("txtNewPassword")
        self.verticalLayout.addWidget(self.txtNewPassword)
        self.btnDeletePassword = QtWidgets.QPushButton(self.centralwidget)
        self.btnDeletePassword.setStyleSheet("background-color: rgb(192, 136, 205);")
        self.btnDeletePassword.setObjectName("btnDeletePassword")
        self.verticalLayout.addWidget(self.btnDeletePassword)
        self.btnNewPassword_3 = QtWidgets.QPushButton(self.centralwidget)
        self.btnNewPassword_3.setStyleSheet("background-color: rgb(192, 136, 205);")
        self.btnNewPassword_3.setObjectName("btnNewPassword_3")
        self.verticalLayout.addWidget(self.btnNewPassword_3)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setStyleSheet("background-color: rgb(99, 4, 143);")
        self.listWidget.setObjectName("listWidget")
        self.horizontalLayout_2.addWidget(self.listWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.actionOpen_File = QtWidgets.QAction(MainWindow)
        self.actionOpen_File.setObjectName("actionOpen_File")
        self.actionEnter_New_Password = QtWidgets.QAction(MainWindow)
        self.actionEnter_New_Password.setObjectName("actionEnter_New_Password")
        self.actionDelete_password = QtWidgets.QAction(MainWindow)
        self.actionDelete_password.setObjectName("actionDelete_password")
        self.actionInfo = QtWidgets.QAction(MainWindow)
        self.actionInfo.setObjectName("actionInfo")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnNewPassword.setText(_translate("MainWindow", "Add a new Password"))
        self.txtNewPassword.setPlaceholderText(_translate("MainWindow", "Enter new password here"))
        self.btnDeletePassword.setText(_translate("MainWindow", "Delete Selected Password"))
        self.btnNewPassword_3.setText(_translate("MainWindow", "Exit"))
        self.actionOpen_File.setText(_translate("MainWindow", "Open File"))
        self.actionEnter_New_Password.setText(_translate("MainWindow", "Add password"))
        self.actionDelete_password.setText(_translate("MainWindow", "Delete password"))
        self.actionInfo.setText(_translate("MainWindow", "Info"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
